config/routes.rb
Rails.application.routes.draw do
  root to: "shounins#new"
  resources :shounins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shounin.rb
class Shounin < ApplicationRecord
  validates :description, presence: true
  validates :description, exclusion: { in: %w(お世話になっております。) }
  include FriendlyId
  friendly_id :uid
  before_create do
    self.uid = SecureRandom.hex(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shounins_controller.rb
# coding: utf-8

class ShouninsController < ApplicationController
  before_action :set_shounin, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with :name => ENV['BASIC_AUTHENTICATE_NAME'], :password => ENV['BASIC_AUTHENTICATE_PASSWORD'], :only => [:index, :edit]
  

  # GET /shounins
  def index
    @shounins = Shounin.all
  end

  # GET /shounins/1
  def show
  end

  # GET /shounins/new
  def new
    @shounin = Shounin.new
  end

  # GET /shounins/1/edit
  def edit
  end

  # POST /shounins
  def create
    @shounin = Shounin.new(shounin_params)

    if @shounin.save
      redirect_to @shounin, notice: '承認申請フォームが作成されました！'
    else
      render :new
    end
  end

  # PATCH/PUT /shounins/1
  def update
    if @shounin.update(shounin_params)
      redirect_to @shounin, notice: '承認申請フォームが更新されました！'
    else
      render :edit
    end
  end

  # DELETE /shounins/1
  def destroy
    @shounin.destroy
    redirect_to shounins_url, notice: '承認申請フォームが削除されました！'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shounin
      @shounin = Shounin.friendly.find(params[:id])
      render json: { message: 'ないよ'} if @shounin.id == params[:id].to_i
    end

    # Only allow a trusted parameter "white list" through.
    def shounin_params
      params.require(:shounin).permit(:url, :description, :email, :approval, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shounins_helper.rb
module ShouninsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>



    <title>承認さん</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style="background-color:#fffafa">
    <%= image_tag 'logo.png', :size => '480x136' %>
    <h1>承認さん</h1>
    <h3>30秒で作れる！カンタン承認フォーム</h3>



    <%= yield %>
  </body>
</html>

app/views/shounins/_form.html.erb
<%= form_for(shounin) do |f| %>
  <% if shounin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shounin.errors.count, "error") %> prohibited this shounin from being saved:</h2>

      <ul>
      <% shounin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :size => "30x10" %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <% if shounin.persisted? %>
    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit '登録', :class=>"button"%>
  </div>
<% end %>

app/views/shounins/edit.html.erb
<h1>Editing Shounin</h1>

<%= render 'form', shounin: @shounin %>

<%= link_to 'Show', @shounin %> |
<%= link_to 'Back', shounins_path %>

app/views/shounins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shounins</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Description</th>
      <th>Email</th>
      <th>Approval</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shounins.each do |shounin| %>
      <tr>
        <td><%= shounin.url %></td>
        <td><%= shounin.description %></td>
        <td><%= shounin.email %></td>
        <td><%= shounin.approval %></td>
        <td><%= shounin.comment %></td>
        <td><%= link_to 'Show', shounin %></td>
        <td><%= link_to 'Edit', edit_shounin_path(shounin) %></td>
        <td><%= link_to 'Destroy', shounin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shounin', new_shounin_path, class: "button"  %>

app/views/shounins/new.html.erb
<%= render 'form', shounin: @shounin %>

app/views/shounins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @shounin.description %>
</p>

<%= form_for @shounin do |f| %>
  <div class="field" >
    <%= f.label :approval %>
  </div>
  <% if @shounin.approval.nil? %>
      <span>承認します</span>
      <%= f.radio_button :approval, '1' %>
      <span>承認しません</span>
      <%= f.radio_button :approval, '0' %>
      <div class="actions">
          <%= f.submit '確定', :class=>"button"%>
      </div>
  <% end %>
  <% if @shounin.approval==false %>
      <% unless @shounin.comment %>
    <%= f.text_area :comment, id: "textarea" %>
    <%= f.submit %>
      <% end %>
  <% end %>
<% end %>
    <!-- <button id="show-textarea"> 承認しません </button> -->
  <% unless @shounin.approval.nil? %>
    <% if @shounin.approval %>
      <p>承認します</p>
      <% else %>
      <p>承認しません</p>
      <p><%= @shounin.comment %><p>
    <% end %>
  <% end %>

<%= link_to 'Edit', edit_shounin_path(@shounin), class: "button" %>
<%= link_to 'Back', shounins_path %>

<!-- <script type="text/javascript">
$('#textarea').hide();
$('#show-textarea').click(function(){
  $('#textarea').show();
});
</script> -->